version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "daily"
    target-branch: master
  - package-ecosystem: "cargo"
    directory: "aft/"
    schedule:
      interval: "daily"
    target-branch: master
  - package-ecosystem: "cargo"
    directory: "aft-crypto/"
    schedule:
      interval: "daily"
    target-branch: master
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    target-branch: master
