[package]
name = "aft-crypto"
version = "1.0.0"
edition = "2021"

[dependencies]
rand_core = {version = "0.6", default-features = false}
aes-gcm = "0.10"
x25519-dalek = "1"
scrypt = "0.10"
rand = "0.8"
zeroize = "1.5"
