name: Rust

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - "LICENSE"
      - "README.md"
      - "SECURITY.MD"
      - ".gitignore"
      - ".config"
  pull_request:
    branches: [ "master" ]
    
env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build Release
        run: cargo build --release --verbose
      - uses: actions/upload-artifact@v3.1.3
        with:
          name: aft-ubuntu
          path: target/release/aft
