name: Rust

on:
  push:
    branches: [ "master" ]
    tags: ["[0-9]+.[0-9]+.[0-9]+"]
    paths-ignore:
      - "LICENSE-MIT"
      - "LICENSE-APACHE"
      - "README.md"
      - "SECURITY.MD"
      - ".gitignore"
      - ".config"
      - "docs/**"
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  linux-x86_64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Release
        run: cargo build --release --verbose

      - uses: actions/upload-artifact@v3.1.3
        with:
          name: aft-linux-x86_64
          path: target/release/aft

  publish-release:
    runs-on: ubuntu-latest
    needs: [linux-x86_64]
    permissions:
      contents: write
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - uses: actions/checkout@v3

      - name: Create release
        id: create_release
        uses: softprops/action-gh-release@v1
        # Publish a release only when a new tag is pushed
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "# What's new since the latest release"
          files: aft-linux-x86_64
          generate_release_notes: true
          draft: true
          prerelease: false
